FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
#Restore dotnet packages
COPY *.csproj ./
RUN dotnet restore

#Restore npm packages
COPY package.json ./
RUN npm install

#Webpack build
COPY webpack.config.js .
COPY .babelrc .
COPY src/ ./src/
RUN npm run webpack

#Build .net dll 
COPY . .
RUN dotnet build -c Release -o /app

FROM build as publish
RUN dotnet publish -c Release -o /app

# Brand new image, but with output of 'publish'. Will make final image nice and small.
FROM base AS final
COPY --from=publish app/ .
ENTRYPOINT ["dotnet", "MaxHrCalculator.dll"]
